<?php

namespace Database\Seeders;

use App\Models\ClubNews;
use Illuminate\Database\Seeder;

class ClubNewsSeeder extends Seeder
{
    public function run()
    {
        $news = [
            [
                'sn' => '138800',
                'language' => 'TS',
                'title' => '串聯藝文、親子及市集體驗　桃園市2026 High 龜山搖滾音樂節《未來光城：光城登入站》重磅登場',
                'img' => '/asd_files/s2026081122072930.jpg',
                'img_w' => 1024,
                'img_h' => 682,
                'date' => '2026-08-11',
                'location' => '宜蘭縣',
                'excerpt' => null,
                'city' => '桃園市',
                'district' => '龜山區',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '音樂活動',
                'content' => '<p>串聯藝文、親子及市集體驗　桃園市2026 High 龜山搖滾音樂節《未來光城：光城登入站》重磅登場</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138795',
                'language' => 'TS',
                'title' => '史努比空降六福村同慶生日！8月限定優惠接力登場　造型咖哩飯、限量針織袋與限定餐點套票限量開搶',
                'img' => '/asd_files/s2026081121454120.jpg',
                'img_w' => 1024,
                'img_h' => 682,
                'date' => '2026-08-11',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹市',
                'district' => '關西鎮',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '娛樂活動',
                'content' => '<p>史努比空降六福村同慶生日！8月限定優惠接力登場</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138784',
                'language' => 'TS',
                'title' => '郭添貴接任一卡通票證公司董事長  領航一卡通開創新局',
                'img' => '/asd_files/s2026081120521870.jpg',
                'img_w' => 1024,
                'img_h' => 1024,
                'date' => '2026-08-11',
                'location' => '高雄市',
                'excerpt' => null,
                'city' => '台北市',
                'district' => '信義區',
                'village' => '',
                'source' => '視傳媒 - 商業新聞',
                'category' => '商業活動',
                'content' => '<p>郭添貴接任一卡通票證公司董事長  領航一卡通開創新局</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138727',
                'language' => 'TS',
                'title' => '桃竹苗分署竹北就業中心8/14日現場徵才　邀集25家知名企業提供1610個優質職缺薪資上看10萬元！',
                'img' => '/asd_files/s2026081113422070.jpg',
                'img_w' => 1024,
                'img_h' => 683,
                'date' => '2026-08-11',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹縣',
                'district' => '竹北市',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '徵才活動',
                'content' => '<p>桃竹苗分署竹北就業中心8/14日現場徵才　邀集25家知名企業提供1610個優質職缺薪資上看10萬元！</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138659',
                'language' => 'TS',
                'title' => '強化全球供應產能、響應全球客戶需求　億光泰國新廠動土預計2027年下半年完工並投入量產貢獻營收',
                'img' => '/asd_files/s2026081019410220.jpg',
                'img_w' => 1024,
                'img_h' => 682,
                'date' => '2026-08-10',
                'location' => '',
                'excerpt' => null,
                'city' => '桃園市',
                'district' => '平鎮區',
                'village' => '',
                'source' => '視傳媒 - 商業新聞',
                'category' => '商業活動',
                'content' => '<p>強化全球供應產能、響應全球客戶需求　億光泰國新廠動土預計2027年下半年完工並投入量產貢獻營收</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138615',
                'language' => 'TS',
                'title' => '海洋文化x在地美食x音樂展演x親子互動x啤酒文化　 115年竹南觀光文化季「逐南風．調啤趣2.0」8/22-23登場',
                'img' => '/asd_files/s2026081013412620.jpg',
                'img_w' => 1024,
                'img_h' => 682,
                'date' => '2026-08-10',
                'location' => '',
                'excerpt' => null,
                'city' => '苗栗縣',
                'district' => '竹南鎮',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '觀光活動',
                'content' => '<p>海洋文化x在地美食x音樂展演x親子互動x啤酒文化　 115年竹南觀光文化季「逐南風．調啤趣2.0」8/22-23登場</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138511',
                'language' => 'TS',
                'title' => '高雄市第51屆模範父親表揚大會 高雄市福建同鄉會理事長陳國鑫 獲選模範父親 各界祝福',
                'img' => '/asd_files/s2026080900173880.jpg',
                'img_w' => 1024,
                'img_h' => 871,
                'date' => '2026-08-09',
                'location' => '高雄市',
                'excerpt' => null,
                'city' => '高雄市',
                'district' => '左營區',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '社會活動',
                'content' => '<p>高雄市第51屆模範父親表揚大會 高雄市福建同鄉會理事長陳國鑫 獲選模範父親 各界祝福</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138484',
                'language' => 'TS',
                'title' => '中山大學護理系走進霧台　跨文化照護教育從部落開始',
                'img' => '/asd_files/s20260808161119100.jpg',
                'img_w' => 1024,
                'img_h' => 577,
                'date' => '2026-08-08',
                'location' => '高雄市',
                'excerpt' => null,
                'city' => '高雄市',
                'district' => '鼓山區',
                'village' => '',
                'source' => '視傳媒 - 教育新聞',
                'category' => '教育活動',
                'content' => '<p>中山大學護理系走進霧台　跨文化照護教育從部落開始</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138432',
                'language' => 'TS',
                'title' => '國際物流因戰火停擺！約旦母女面臨居留證過期困境　　移民署竹市站5個月一路陪伴暖心守護順利延期留臺',
                'img' => '/asd_files/s2026080721222090.jpg',
                'img_w' => 1024,
                'img_h' => 683,
                'date' => '2026-08-07',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹市',
                'district' => '東區',
                'village' => '',
                'source' => '視傳媒 - 社會新聞',
                'category' => '社會公益',
                'content' => '<p>國際物流因戰火停擺！約旦母女面臨居留證過期困境</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138429',
                'language' => 'TS',
                'title' => '從公文自動化到作業初審　敏實科大打造多模型協作數位校務團隊引領智慧校園革命邁向AI Agent 大學',
                'img' => '/asd_files/s2026080720215110.jpg',
                'img_w' => 1024,
                'img_h' => 682,
                'date' => '2026-08-07',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹市',
                'district' => '東區',
                'village' => '',
                'source' => '視傳媒 - 教育新聞',
                'category' => '教育活動',
                'content' => '<p>從公文自動化到作業初審　敏實科大打造多模型協作數位校務團隊引領智慧校園革命邁向AI Agent 大學</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138399',
                'language' => 'TS',
                'title' => '桃竹苗分署「2026暑期遊程」　串聯8家民間團體、11條深度旅遊路線感受桃竹苗豐富的人文與自然魅力',
                'img' => '/asd_files/s2026080715304860.jpg',
                'img_w' => 1024,
                'img_h' => 682,
                'date' => '2026-08-07',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹縣',
                'district' => '竹北市',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '旅遊活動',
                'content' => '<p>桃竹苗分署「2026暑期遊程」　串聯8家民間團體、11條深度旅遊路線感受桃竹苗豐富的人文與自然魅力</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138332',
                'language' => 'TS',
                'title' => '台積電等科技大廠帶頭號召！響應喜憨兒中秋「送禮傳愛」　籲請用公共採購與消費促進社會共融',
                'img' => '/asd_files/s2026080622013230.jpg',
                'img_w' => 1024,
                'img_h' => 713,
                'date' => '2026-08-06',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹市',
                'district' => '東區',
                'village' => '',
                'source' => '視傳媒 - 社會新聞',
                'category' => '社會公益',
                'content' => '<p>台積電等科技大廠帶頭號召！響應喜憨兒中秋「送禮傳愛」　籲請用公共採購與消費促進社會共融</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138329',
                'language' => 'TS',
                'title' => '硬實力成創業最強底氣！　紡織廠基層員工43歲中年失業融合職訓打版思維成功開創功能性機能織品藍海',
                'img' => '/asd_files/s2026080620453840.jpg',
                'img_w' => 1024,
                'img_h' => 683,
                'date' => '2026-08-06',
                'location' => '',
                'excerpt' => null,
                'city' => '台中市',
                'district' => '西屯區',
                'village' => '',
                'source' => '視傳媒 - 社會新聞',
                'category' => '社會公益',
                'content' => '<p>硬實力成創業最強底氣！　紡織廠基層員工43歲中年失業融合職訓打版思維成功開創功能性機能織品藍海</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138327',
                'language' => 'TS',
                'title' => '仁愛社福x躉泰食品x新東陽x查理布朗x一之鄉　2026中秋LOVE義賣多款美味優質禮盒懇請各界愛心支持',
                'img' => '/asd_files/s2026080620120880.jpg',
                'img_w' => 1024,
                'img_h' => 375,
                'date' => '2026-08-06',
                'location' => '',
                'excerpt' => null,
                'city' => '台北市',
                'district' => '中正區',
                'village' => '',
                'source' => '視傳媒 - 社會新聞',
                'category' => '社會公益',
                'content' => '<p>仁愛社福x躉泰食品x新東陽x查理布朗x一之鄉　2026中秋LOVE義賣多款美味優質禮盒懇請各界愛心支持</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138316',
                'language' => 'TS',
                'title' => '《婚禮上的小抄》高雄登場 故事工廠公益觀演 邀單親家庭免費看戲 程予希失眠4天後台崩潰！李天柱藏父愛、郭子乾憶病母 編劇劉中薇將演員真實故事放進劇本 更令人動容',
                'img' => '/asd_files/s2026080617591050.jpg',
                'img_w' => 1024,
                'img_h' => 682,
                'date' => '2026-08-06',
                'location' => '高雄市',
                'excerpt' => null,
                'city' => '高雄市',
                'district' => '左營區',
                'village' => '',
                'source' => '視傳媒 - 文教體育',
                'category' => '文藝活動',
                'content' => '<p>《婚禮上的小抄》高雄登場 故事工廠公益觀演 邀單親家庭免費看戲</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138305',
                'language' => 'TS',
                'title' => '陪伴企業邁向低碳轉型打造低碳永續產業示範群聚　花蓮縣府8/18舉辦低碳化暨節能診斷實施方案說明會',
                'img' => '/asd_files/s2026080617161810.jpg',
                'img_w' => 1024,
                'img_h' => 768,
                'date' => '2026-08-06',
                'location' => '',
                'excerpt' => null,
                'city' => '花蓮縣',
                'district' => '花蓮市',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '經濟活動',
                'content' => '<p>陪伴企業邁向低碳轉型打造低碳永續產業示範群聚　花蓮縣府8/18舉辦低碳化暨節能診斷實施方案說明會</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138237',
                'language' => 'TS',
                'title' => '百年飄香！日本銀座天國重磅客座大倉久和，極致天婦羅美味再度登台',
                'img' => '/asd_files/s2026080713383720.jpg',
                'img_w' => 1024,
                'img_h' => 631,
                'date' => '2026-08-06',
                'location' => '',
                'excerpt' => '創立於明治18年（1885年）、擁有141年歷史的東京銀座百年天婦羅名店「銀座天國」，2025年首度來台客座廣受好評，今年8月15日至8月19日再度受邀來台，於大倉久和大飯店山里日本料理限時客座，將百年傳承酥香美味的天婦羅匠藝再次帶到台北，邀請賓客重溫一口入魂的極致風味。',
                'city' => '台北市',
                'district' => '信義區',
                'village' => '',
                'source' => '視傳媒 - 美食新聞',
                'category' => '美食活動',
                'content' => '<p>百年飄香！日本銀座天國重磅客座大倉久和，極致天婦羅美味再度登台</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138208',
                'language' => 'TS',
                'title' => '一年一度的竹塹中元城隍祭正式展開！　邀請全國民眾走進竹市感受兼具歷史底蘊與城市活力的民俗盛典',
                'img' => '/asd_files/s2026080521263340.jpg',
                'img_w' => 1024,
                'img_h' => 576,
                'date' => '2026-08-05',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹市',
                'district' => '北區',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '民俗活動',
                'content' => '<p>一年一度的竹塹中元城隍祭正式展開！　邀請全國民眾走進竹市感受兼具歷史底蘊與城市活力的民俗盛典</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138203',
                'language' => 'TS',
                'title' => '最誠摯佳節祝福！GO多藝團隊公益傳愛八德榮家長輩　多元舞風陪伴歡慶父親節體現敬老尊老精神',
                'img' => '/asd_files/s2026080519371320.jpg',
                'img_w' => 1024,
                'img_h' => 683,
                'date' => '2026-08-05',
                'location' => '',
                'excerpt' => null,
                'city' => '桃園市',
                'district' => '八德區',
                'village' => '',
                'source' => '視傳媒 - 社會新聞',
                'category' => '社會公益',
                'content' => '<p>最誠摯佳節祝福！GO多藝團隊公益傳愛八德榮家長輩　多元舞風陪伴歡慶父親節體現敬老尊老精神</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138186',
                'language' => 'TS',
                'title' => '心路基金會早療寶貝畢典結合運動會　孩子展現學習成果勇敢跨出成長每一步迎向人生下一段精彩旅程',
                'img' => '/asd_files/s2026080518230830.jpg',
                'img_w' => 1024,
                'img_h' => 683,
                'date' => '2026-08-05',
                'location' => '',
                'excerpt' => null,
                'city' => '台北市',
                'district' => '中正區',
                'village' => '',
                'source' => '視傳媒 - 社會新聞',
                'category' => '社會公益',
                'content' => '<p>心路基金會早療寶貝畢典結合運動會　孩子展現學習成果勇敢跨出成長每一步迎向人生下一段精彩旅程</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138180',
                'language' => 'TS',
                'title' => '2026全國第二次羽球排名賽自8/11-8/19火熱開打　甲組及乙組好手齊聚摩拳擦掌爭取最佳成績與榮譽',
                'img' => '/asd_files/s2026080516575440.jpg',
                'img_w' => 1024,
                'img_h' => 869,
                'date' => '2026-08-05',
                'location' => '',
                'excerpt' => null,
                'city' => '台北市',
                'district' => '信義區',
                'village' => '',
                'source' => '視傳媒 - 體育新聞',
                'category' => '體育活動',
                'content' => '<p>2026全國第二次羽球排名賽自8/11-8/19火熱開打　甲組及乙組好手齊聚摩拳擦掌爭取最佳成績與榮譽</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138132',
                'language' => 'TS',
                'title' => '桃竹苗分署與台南應用科大共同培訓選手呂羽昕　五年磨一劍勇奪第56屆全國技能競賽中式服裝職類金牌',
                'img' => '/asd_files/s2026080514370320.jpg',
                'img_w' => 1024,
                'img_h' => 683,
                'date' => '2026-08-05',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹縣',
                'district' => '竹北市',
                'village' => '',
                'source' => '視傳媒 - 教育新聞',
                'category' => '教育活動',
                'content' => '<p>桃竹苗分署與台南應用科大共同培訓選手呂羽昕　五年磨一劍勇奪第56屆全國技能競賽中式服裝職類金牌</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138075',
                'language' => 'TS',
                'title' => '結合啤酒、美食、音樂及海港景致　竹市夏日乾杯活動圓滿成功打造北臺灣具代表性夏日啤酒音樂活動',
                'img' => '/asd_files/s20260804211259100.jpg',
                'img_w' => 1024,
                'img_h' => 768,
                'date' => '2026-08-04',
                'location' => '',
                'excerpt' => null,
                'city' => '新竹市',
                'district' => '北區',
                'village' => '',
                'source' => '視傳媒 - 地方新聞',
                'category' => '觀光活動',
                'content' => '<p>結合啤酒、美食、音樂及海港景致　竹市夏日乾杯活動圓滿成功打造北臺灣具代表性夏日啤酒音樂活動</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
            [
                'sn' => '138071',
                'language' => 'TS',
                'title' => '國科會通過中科2件新投資案　中科園區今年累計引進10家新投資案共計投資總額新臺幣52.98億元',
                'img' => '/asd_files/s2026080419365790.jpg',
                'img_w' => 1024,
                'img_h' => 683,
                'date' => '2026-08-04',
                'location' => '',
                'excerpt' => null,
                'city' => '台中市',
                'district' => '西屯區',
                'village' => '',
                'source' => '視傳媒 - 經濟新聞',
                'category' => '經濟活動',
                'content' => '<p>國科會通過中科2件新投資案　中科園區今年累計引進10家新投資案共計投資總額新臺幣52.98億元</p>',
                'is_excluded' => false,
                'views' => 0,
            ],
        ];

        foreach ($news as $item) {
            ClubNews::updateOrCreate(['sn' => $item['sn']], $item);
        }
    }
}