<?php

namespace Database\Seeders;

use App\Models\Director;
use Illuminate\Database\Seeder;

class DirectorSeeder extends Seeder
{
    public function run(): void
    {
        $directors = [
            [
                'sn'             => '5529',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => true,
                'sort_order'     => 1,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '現任會長',
                'title'          => '[第三屆會長] 林頌恒',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072214434030.png',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5530',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => true,
                'sort_order'     => 2,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '歷屆會長',
                'title'          => '[創會長/第二屆會長] 張志豪',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s20260722144450100.png',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5522',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 3,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '歷屆會長',
                'title'          => '[榮譽創會長] 郭培權',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072217170280.png',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5549',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 4,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務幹部',
                'title'          => '[財務長] 王淑如',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072216514560.png',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5548',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 5,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務幹部',
                'title'          => '[秘書長] 梁晏誠',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072216505320.png',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5541',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 6,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[法制顧問] 羅詠騰',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5540',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 7,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 蔡麗青',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5539',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 8,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 朱正軒',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5538',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 9,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 蔡宗豪',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5537',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 10,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 呂根銘',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5536',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 11,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 黃瓊慧',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5535',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 12,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 陳富群',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5534',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 13,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 陳燦榮',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5533',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 14,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 夏立岩',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5532',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 15,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '會務顧問',
                'title'          => '[會務顧問] 吳俊賦',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/202607221414355319.png',
                'img_w'          => 1024,
                'img_h'          => 763,
                'views'          => 0,
            ],
            [
                'sn'             => '5527',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 16,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '理監事',
                'title'          => '[常務監事] 鄒耀德',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072211272880.png',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5526',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 17,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '理監事',
                'title'          => '[監事/榮譽會長] 曾翊銘',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072211264410.png',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5525',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 18,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '理監事',
                'title'          => '[監事] 吳宗融',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072211133440.png',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5524',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 19,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '理監事',
                'title'          => '[監事] 謝信安',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072211041880.jpg',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
            [
                'sn'             => '5523',
                'language'       => 'TS',
                'status'         => true,
                'show_on_home'   => false,
                'sort_order'     => 20,
                'published_date' => '2026-07-22',
                'end_date'       => '2200-12-31',
                'category'       => '理監事',
                'title'          => '[監事] 劉ㄧ德',
                'name'           => '',
                'brief'          => '',
                'content'        => '',
                'has_photo'      => true,
                'img'            => '/works_files/s2026072211034850.jpg',
                'img_w'          => 775,
                'img_h'          => 1024,
                'views'          => 0,
            ],
        ];

        foreach ($directors as $director) {
            Director::create($director);
        }
    }
}
